# Generated by Django 3.2.8 on 2021-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20211010_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.CharField(default='Tvs', max_length=255),
        ),
    ]
