# Generated by Django 3.2.7 on 2021-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_products_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='products',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
