# Generated by Django 3.2.7 on 2021-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/avatar.png', null=True, upload_to='static/images/profile'),
        ),
    ]
